# Common settings for all profiles
server:
  port: ${PORT:8080}

spring:
  application:
    name: l2q
  # Default profile will be 'dev' for local development
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    # For production (Railway), these will be overridden by environment variables
    url: ${DATABASE_URL:#{null}}
    username: ${DB_USERNAME:#{null}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

# Gemini API Configuration
gemini:
  api:
    key: AIzaSyB_E-kjE1e-61UrzEaqnSfKUXeA94StRjQ

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Common logging configuration
logging:
  level:
    com:
      kopo:
        l2q: INFO
    org:
      springframework:
        web:
          servlet: WARN
        boot: WARN
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: WARN
    io:
      socket:
        io: WARN
    root: WARN
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  # MySQL Database Configuration for development
  datasource:
    url: jdbc:mysql://root:JGJFUGisfkXffKhmukWJNFnUejafJltL@turntable.proxy.rlwy.net:55965/railway
    username: root
    password: JGJFUGisfkXffKhmukWJNFnUejafJltL
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

logging:
  level:
    org:
      springframework:
        web: WARN
      hibernate:
        SQL: WARN

